### ISSUE TITLE
Does the python pipeline include sequence alignment and allele calling functions?

### ISSUE THREAD

**Issue by peipp410** [ShouWenWang-Lab/snakemake_DARLIN#8]
Hi! Thanks for providing a python-based version of CARLIN pipeline. We want to modify the arguments to run on our own sequencing data and reference from a different experiment protocol. However, I can't locate where the function for sequence alignment is. It seems that the MosaicLineage directly inputs the matlab object from the original CARLIN pipeline?
Thanks!

**Comment by ShouWenWang** [comment]
The snakemake_DARLIN has two ways to analyze the CARLIN data.
1, the matlab way. It relies on the matlaib CARLIN pipeline. To modify the reference sequence, you need to change it here:
https://github.com/ShouWenWang-Lab/Custom_CARLIN/tree/main/%40CARLIN_def
https://github.com/ShouWenWang-Lab/Custom_CARLIN/tree/main/cfg
This change is big and challenging.

2, there is also a python based method. This method, however, does not call mutations in the sequence like the matlab way. It only identifies the DARLIN sequence, and use difference sequences to call different clones. We implemented a single-cell version. But changing it to bulk should be also easy.
https://github.com/ShouWenWang-Lab/snakemake_DARLIN/blob/master/QC/single_cell_DARLIN-10x.ipynb

--
Shou-Wen Wang, Ph.D.
Principal Investigator
School of Life Sciences | School of Science
Westlake University
Shilongshan ST #18, Xihu, Hangzhou, Zhejiang
https://www.shouwenwang-lab.com/



From: Jiazheng Pei ***@***.***>
Date: Friday, June 14, 2024 at 10:45 AM
To: ShouWenWang-Lab/snakemake_DARLIN ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ShouWenWang-Lab/snakemake_DARLIN] Does the python pipeline include sequence alignment and allele calling functions? (Issue #8)

Hi! Thanks for providing a python-based version of CARLIN pipeline. We want to modify the arguments to run on our own sequencing data and reference from a different experiment protocol. However, I can't locate where the function for sequence alignment is. It seems that the MosaicLineage directly inputs the matlab object from the original CARLIN pipeline?
Thanks!

**Comment by peipp410** [comment]
Thank you! I'll try that.

**Comment by peipp410** [comment]
Hello, I encountered another problem. Is this process suitable for running large files? I have a double-end sequencing file, each about 2GB. When running the script using a 64-core server, the following error still occurs.
<img width="679" alt="截屏2024-06-28 18 08 17" src="https://github.com/ShouWenWang-Lab/snakemake_DARLIN/assets/59289157/a3845fb0-901c-4106-ad71-50734ccb898d">

**Comment by ShouWenWang** [comment]
I have not encountered this problem before. But the preprocessing could be resource intensive. You could subset your data into several parts, process each separately, and merge the final results together.

 ――
Shou-Wen Wang, PhD
Principal Investigator
School of Life Sciences | School of Sciences
Westlake University
Shilongshan ST #18, Xihu, Hangzhou, Zhejiang
https://www.shouwenwang-lab.com/


________________________________

**Comment by peipp410** [comment]
OK! Thank you!

**Comment by jzussman** [comment]
Would it be possible for you to provide a bulk version of the python method for allele calling? Alternatively, if you don't have the bandwidth at the moment, could you instruct me on how I could most easily adapt the existing python pipeline to bulk sequence data?

In addition, would adapting the existing python-based single-cell pipeline to the newer 10xV4 chemistry be as simple as adding in the 10xV4 barcode list to /reference? What else would be required to complete this configuration? I have successfully generated this config using the MATLAB CARLIN pipeline version, but am not sure how I would do so in the python version.
